from typing import Set, List
from pydantic import BaseModel
from app.models import FlagType


class Ingredient(BaseModel):
    id: str
    name: str
    category: str
    calories_per_100g: float
    protein_per_100g: float
    carbs_per_100g: float
    fat_per_100g: float
    flags: Set[FlagType] = set()

    model_config = {"arbitrary_types_allowed": True}


INGREDIENTS_DB: List[Ingredient] = [
    Ingredient(
        id="chicken_breast",
        name="鸡胸肉",
        category="肉类",
        calories_per_100g=165.0,
        protein_per_100g=31.0,
        carbs_per_100g=0.0,
        fat_per_100g=3.6,
        flags=set(),
    ),
    Ingredient(
        id="beef_lean",
        name="瘦牛肉",
        category="肉类",
        calories_per_100g=250.0,
        protein_per_100g=26.0,
        carbs_per_100g=0.0,
        fat_per_100g=15.0,
        flags={FlagType.HALAL},
    ),
    Ingredient(
        id="pork_lean",
        name="瘦猪肉",
        category="肉类",
        calories_per_100g=143.0,
        protein_per_100g=20.3,
        carbs_per_100g=1.5,
        fat_per_100g=6.2,
        flags=set(),
    ),
    Ingredient(
        id="salmon",
        name="三文鱼",
        category="水产",
        calories_per_100g=208.0,
        protein_per_100g=20.0,
        carbs_per_100g=0.0,
        fat_per_100g=13.0,
        flags={FlagType.ALLERGY_SEAFOOD},
    ),
    Ingredient(
        id="shrimp",
        name="虾",
        category="水产",
        calories_per_100g=99.0,
        protein_per_100g=24.0,
        carbs_per_100g=0.2,
        fat_per_100g=0.3,
        flags={FlagType.ALLERGY_SEAFOOD},
    ),
    Ingredient(
        id="egg",
        name="鸡蛋",
        category="蛋类",
        calories_per_100g=155.0,
        protein_per_100g=13.0,
        carbs_per_100g=1.1,
        fat_per_100g=11.0,
        flags={FlagType.VEGETARIAN},
    ),
    Ingredient(
        id="egg_white",
        name="蛋白",
        category="蛋类",
        calories_per_100g=52.0,
        protein_per_100g=11.0,
        carbs_per_100g=0.7,
        fat_per_100g=0.2,
        flags={FlagType.VEGETARIAN},
    ),
    Ingredient(
        id="milk",
        name="牛奶",
        category="乳制品",
        calories_per_100g=54.0,
        protein_per_100g=3.2,
        carbs_per_100g=5.0,
        fat_per_100g=3.2,
        flags={FlagType.ALLERGY_LACTOSE, FlagType.VEGETARIAN},
    ),
    Ingredient(
        id="yogurt",
        name="酸奶",
        category="乳制品",
        calories_per_100g=72.0,
        protein_per_100g=3.5,
        carbs_per_100g=9.0,
        fat_per_100g=2.7,
        flags={FlagType.ALLERGY_LACTOSE, FlagType.VEGETARIAN},
    ),
    Ingredient(
        id="cheese",
        name="奶酪",
        category="乳制品",
        calories_per_100g=402.0,
        protein_per_100g=25.0,
        carbs_per_100g=1.3,
        fat_per_100g=33.0,
        flags={FlagType.ALLERGY_LACTOSE, FlagType.VEGETARIAN},
    ),
    Ingredient(
        id="tofu",
        name="豆腐",
        category="豆制品",
        calories_per_100g=76.0,
        protein_per_100g=8.0,
        carbs_per_100g=1.9,
        fat_per_100g=4.8,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="soy_milk",
        name="豆浆",
        category="豆制品",
        calories_per_100g=33.0,
        protein_per_100g=3.3,
        carbs_per_100g=2.0,
        fat_per_100g=1.6,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="rice",
        name="大米",
        category="主食",
        calories_per_100g=365.0,
        protein_per_100g=7.0,
        carbs_per_100g=79.0,
        fat_per_100g=0.7,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="oats",
        name="燕麦",
        category="主食",
        calories_per_100g=389.0,
        protein_per_100g=17.0,
        carbs_per_100g=66.0,
        fat_per_100g=7.0,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER, FlagType.ALLERGY_GLUTEN},
    ),
    Ingredient(
        id="bread_whole",
        name="全麦面包",
        category="主食",
        calories_per_100g=247.0,
        protein_per_100g=13.0,
        carbs_per_100g=41.0,
        fat_per_100g=4.2,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.ALLERGY_GLUTEN},
    ),
    Ingredient(
        id="sweet_potato",
        name="红薯",
        category="主食",
        calories_per_100g=86.0,
        protein_per_100g=1.6,
        carbs_per_100g=20.0,
        fat_per_100g=0.1,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER, FlagType.ALLERGY_GLUTEN},
    ),
    Ingredient(
        id="broccoli",
        name="西兰花",
        category="蔬菜",
        calories_per_100g=34.0,
        protein_per_100g=2.8,
        carbs_per_100g=7.0,
        fat_per_100g=0.4,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="spinach",
        name="菠菜",
        category="蔬菜",
        calories_per_100g=23.0,
        protein_per_100g=2.9,
        carbs_per_100g=3.6,
        fat_per_100g=0.4,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="carrot",
        name="胡萝卜",
        category="蔬菜",
        calories_per_100g=41.0,
        protein_per_100g=0.9,
        carbs_per_100g=10.0,
        fat_per_100g=0.2,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="tomato",
        name="番茄",
        category="蔬菜",
        calories_per_100g=18.0,
        protein_per_100g=0.9,
        carbs_per_100g=4.0,
        fat_per_100g=0.2,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="cucumber",
        name="黄瓜",
        category="蔬菜",
        calories_per_100g=16.0,
        protein_per_100g=0.7,
        carbs_per_100g=3.6,
        fat_per_100g=0.1,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="apple",
        name="苹果",
        category="水果",
        calories_per_100g=52.0,
        protein_per_100g=0.3,
        carbs_per_100g=14.0,
        fat_per_100g=0.2,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="banana",
        name="香蕉",
        category="水果",
        calories_per_100g=89.0,
        protein_per_100g=1.1,
        carbs_per_100g=23.0,
        fat_per_100g=0.3,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="peanut",
        name="花生",
        category="坚果",
        calories_per_100g=567.0,
        protein_per_100g=25.0,
        carbs_per_100g=16.0,
        fat_per_100g=49.0,
        flags={FlagType.ALLERGY_PEANUT, FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="almond",
        name="杏仁",
        category="坚果",
        calories_per_100g=579.0,
        protein_per_100g=21.0,
        carbs_per_100g=22.0,
        fat_per_100g=50.0,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="avocado",
        name="牛油果",
        category="水果",
        calories_per_100g=160.0,
        protein_per_100g=2.0,
        carbs_per_100g=9.0,
        fat_per_100g=15.0,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="olive_oil",
        name="橄榄油",
        category="油脂",
        calories_per_100g=884.0,
        protein_per_100g=0.0,
        carbs_per_100g=0.0,
        fat_per_100g=100.0,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="quinoa",
        name="藜麦",
        category="主食",
        calories_per_100g=368.0,
        protein_per_100g=14.1,
        carbs_per_100g=64.2,
        fat_per_100g=6.1,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="chickpea",
        name="鹰嘴豆",
        category="豆类",
        calories_per_100g=364.0,
        protein_per_100g=19.0,
        carbs_per_100g=61.0,
        fat_per_100g=6.0,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
    Ingredient(
        id="lentil",
        name="小扁豆",
        category="豆类",
        calories_per_100g=352.0,
        protein_per_100g=26.0,
        carbs_per_100g=60.0,
        fat_per_100g=1.1,
        flags={FlagType.VEGETARIAN, FlagType.VEGAN, FlagType.HALAL, FlagType.KOSHER},
    ),
]


def get_all_ingredients() -> List[Ingredient]:
    return INGREDIENTS_DB.copy()


def get_ingredient_by_id(ingredient_id: str) -> Ingredient | None:
    for ing in INGREDIENTS_DB:
        if ing.id == ingredient_id:
            return ing
    return None


def get_ingredients_by_category(category: str) -> List[Ingredient]:
    return [ing for ing in INGREDIENTS_DB if ing.category == category]
